"use client";

import BlogCard from "./m/BlogCard";

export default function AllProjectCard() {
  const cardData = [
    {
      id: "1",
      title: "Title",
      date: "2024-12-14",
      avatar: "https://nextui.org/images/breathing-app-icon.jpeg",
      image: "https://nextui.org/images/album-cover.png",
      alt: "First project",
      tag: "Css",
      description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. ",
    },
    {
      id: "2",
      title: "Title",
      date: "2024-12-14",
      avatar: "https://nextui.org/images/breathing-app-icon.jpeg",
      image: "https://nextui.org/images/album-cover.png",
      alt: "First project",
      tag: "Html",
      description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. ",
    },
    {
      id: "3",
      title: "Title",
      date: "2024-12-14",
      avatar: "https://nextui.org/images/breathing-app-icon.jpeg",
      image: "https://nextui.org/images/album-cover.png",
      alt: "First project",
      tag: "Html",
      description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. ",
    },
    {
      id: "4",
      title: "Title",
      date: "2024-12-14",
      avatar: "https://nextui.org/images/breathing-app-icon.jpeg",
      image: "https://nextui.org/images/album-cover.png",
      alt: "First project",
      tag: "Html",
      description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. ",
    },
    {
      id: "5",
      title: "Title",
      date: "2024-12-14",
      avatar: "https://nextui.org/images/breathing-app-icon.jpeg",
      image: "https://nextui.org/images/album-cover.png",
      alt: "First project",
      tag: "Html",
      description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. ",
    },
    {
      id: "6",
      title: "Title",
      date: "2024-12-14",
      avatar: "https://nextui.org/images/breathing-app-icon.jpeg",
      image: "https://nextui.org/images/album-cover.png",
      alt: "First project",
      tag: "Html",
      description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. ",
    },
    {
      id: "7",
      title: "Title",
      date: "2024-12-14",
      avatar: "https://nextui.org/images/breathing-app-icon.jpeg",
      image: "https://nextui.org/images/album-cover.png",
      alt: "First project",
      tag: "Html",
      description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. ",
    },
    {
      id: "8",
      title: "Title",
      date: "2024-12-14",
      avatar: "https://nextui.org/images/breathing-app-icon.jpeg",
      image: "https://nextui.org/images/album-cover.png",
      alt: "First project",
      tag: "Html",
      description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. ",
    },
    {
      id: "9",
      title: "Title",
      date: "2024-12-14",
      avatar: "https://nextui.org/images/breathing-app-icon.jpeg",
      image: "https://nextui.org/images/album-cover.png",
      alt: "First project",
      tag: "Html",
      description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. ",
    },
    {
      id: "10",
      title: "Title",
      date: "2024-12-14",
      avatar: "https://nextui.org/images/breathing-app-icon.jpeg",
      image: "https://nextui.org/images/album-cover.png",
      alt: "First project",
      tag: "Html",
      description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. ",
    },
  ];

  return <BlogCard cardData={cardData} />;
}
